# Welcome {.unnumbered}

Welcome to the quarto book of our project. This project was developed as part of the university courses Spatio-temporal Data by Dr. Guido Kraemer and Scientific Writing by Prof. Dr. Miguel Mahecha. This book contains an introduction to our project with the documented code used for this analysis and their results. 

For more information on how this book was created, or how to install the Python environment, see our [GitLab repository](https://git.sc.uni-leipzig.de/ss2024-12-geo-m-ds02/ndvi-time-series-prediction).

The logo of this book is generated by AI.

## Authors

Lioba Braun, [l.braun@studserv.uni-leipzig.de](l.braun@studserv.uni-leipzig.de), 3763791

Charlotte Göhler, [charlotte.goehler@studserv.uni-leipzig.de](charlotte.goehler@studserv.uni-leipzig.de), 3748735

Sebastian Löblein, [sy82leti@studserv.uni-leipzig.de](sy82leti@studserv.uni-leipzig.de), 3780681

Finja Baumer, [fb30qaca@studserv.uni-leipzig.de](fb30qaca@studserv.uni-leipzig.de), 3759991

Kimberly Jahn, [an24onuc@studserv.uni-leipzig.de](an24onuc@studserv.uni-leipzig.de), 3763197

## Acknowlegdement

We would like to thank the European Space Agency for sponsoring the JupyterLab instance we used for our analysis.
